backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

site_url: https://sogoodman.netlify.app/

collections:
  - name: "posts"
    label: "Posts"
    folder: "source/_posts/"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "更新日期", name: "updated", widget: "datetime", required: false}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "分类", name: "categories", widget: "list"}
      - {label: "封面图", name: "cover", widget: "string", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
